name: Document

on:
  push:
    branches: [root]
  workflow_run:
    types: [completed]
    workflows: [Test]

jobs:
  pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build
        run: |
          python -m pip install Sphinx sphinx_rtd_theme
          mkdir _static
          make clean
          make html
        working-directory: ./docs
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
